### ISSUE TITLE
爬留学板块有点问题

### ISSUE THREAD

**Issue by Chiyin0201** [AKonjac0/spider_cc98#2]
学习天地和科研学术都是能正常运行的
把board改成102之后，报错如下，不知道发生了什么

Traceback (most recent call last):
  File "/home/camp/czy/spider_cc98-spider_cc98/main.py", line 150, in <module>
    spider(workbook_num, board_num)
  File "/home/camp/czy/spider_cc98-spider_cc98/main.py", line 114, in spider
    js_html = json.loads(html)
  File "/home/camp/lhh/miniconda3/envs/ccczy/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/camp/lhh/miniconda3/envs/ccczy/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/camp/lhh/miniconda3/envs/ccczy/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AKonjac0** [comment]
出现json.decoder.JSONDecodeError，可以把代码第8行header里的Authorization改一下，具体见README.
比如，把它改成：
“Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkEyOTQ4RUY3Nzk3RkZFNkQ0OTcyOTQ0ODY5OTU3MkU5IiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE3MTY3MDk3ODUsImV4cCI6MTcxNjcxMzM4NSwiaXNzIjoiaHR0cHM6Ly9vcGVuaWQuY2M5OC5vcmciLCJjbGllbnRfaWQiOiI5YTFmZDIwMC04Njg3LTQ0YjEtNGMyMC0wOGQ1MGE5NmU1Y2QiLCJzdWIiOiI3MzUzNzYiLCJhdXRoX3RpbWUiOjE3MTY1MjkxMTQsImlkcCI6ImxvY2FsIiwidW5pcXVlX25hbWUiOiJBS29uamFjXyIsIm5hbWUiOiJBS29uamFjXyIsImZvcnVtLnByaXZpbGVnZSI6NCwianRpIjoiMzNCRjk3RUNENkRERDBDRUE0REZDMUUwQTQzM0E3ODIiLCJpYXQiOjE3MTY1MjkxMTQsInNjb3BlIjpbImNjOTgtYXBpIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbIkNDOTgiXX0.fuBk4F2FeH10yXG58LhyfyIaDFhgZ4AIzrfq5FjfR3BphAX6l45-qAZz8_fQRqiSYuPZnlKvdJNw-uInLXYxjZ4roCabK0-LlokPEXkD7rsCFvVscFXFJ9YOiUf3f5rf6eIHk9fdacL-cZuwPxgIgN0-eWENtGPYp9pRmVCA9cG3L_FeFIg9T6PowHG-TpK1PoK_6dPORDp4EMR4GRJsM8POUMArqqL1zyVeQ086WvgUDg2j8kIwBGAKoVmgbc8mJkUFrcTKoOchkTX-GYNOL6INLyy_gpLScFvowPpjFSXrSD1kBPaYd4joiu0pTjFCO06kvHLDE4EKtzCbtcdnTA”

**Comment by AKonjac0** [comment]
这个东西是动态刷新的，如果用的时候报错就需要手动换一下。

**Comment by Chiyin0201** [comment]
> 出现json.decoder.JSONDecodeError，可以把代码第8行header里的Authorization改一下，具体见README. 比如，把它改成： “Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkEyOTQ4RUY3Nzk3RkZFNkQ0OTcyOTQ0ODY5OTU3MkU5IiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE3MTY3MDk3ODUsImV4cCI6MTcxNjcxMzM4NSwiaXNzIjoiaHR0cHM6Ly9vcGVuaWQuY2M5OC5vcmciLCJjbGllbnRfaWQiOiI5YTFmZDIwMC04Njg3LTQ0YjEtNGMyMC0wOGQ1MGE5NmU1Y2QiLCJzdWIiOiI3MzUzNzYiLCJhdXRoX3RpbWUiOjE3MTY1MjkxMTQsImlkcCI6ImxvY2FsIiwidW5pcXVlX25hbWUiOiJBS29uamFjXyIsIm5hbWUiOiJBS29uamFjXyIsImZvcnVtLnByaXZpbGVnZSI6NCwianRpIjoiMzNCRjk3RUNENkRERDBDRUE0REZDMUUwQTQzM0E3ODIiLCJpYXQiOjE3MTY1MjkxMTQsInNjb3BlIjpbImNjOTgtYXBpIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbIkNDOTgiXX0.fuBk4F2FeH10yXG58LhyfyIaDFhgZ4AIzrfq5FjfR3BphAX6l45-qAZz8_fQRqiSYuPZnlKvdJNw-uInLXYxjZ4roCabK0-LlokPEXkD7rsCFvVscFXFJ9YOiUf3f5rf6eIHk9fdacL-cZuwPxgIgN0-eWENtGPYp9pRmVCA9cG3L_FeFIg9T6PowHG-TpK1PoK_6dPORDp4EMR4GRJsM8POUMArqqL1zyVeQ086WvgUDg2j8kIwBGAKoVmgbc8mJkUFrcTKoOchkTX-GYNOL6INLyy_gpLScFvowPpjFSXrSD1kBPaYd4joiu0pTjFCO06kvHLDE4EKtzCbtcdnTA”

谢了老哥
